version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
      day: "monday"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "svelte"
        versions: ["< 6.0.0"]

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "tuesday"
    open-pull-requests-limit: 10
