host: 0.0.0.0
port: 3000
base_url: http://localhost:3000
db_path: ./data/updu.db
log_level: info
monitors:
    - id: 993191692cba
      name: GitOps TCP Test
      type: tcp
      groups:
        - GitOps
      interval_s: 60
      timeout_s: 10
      enabled: true
      config:
        host: localhost
        port: 3000
    - id: yaml-http-test
      name: YAML HTTP Test
      type: http
      groups:
        - GitOps
      interval_s: 30
      timeout_s: 10
      enabled: true
      config:
        expected_status: 200
        method: GET
        url: https://google.com
