monitors:
  - id: wan-ping
    name: Cloudflare Anycast Ping
    type: ping
    groups: [Network]
    interval: 1m
    config:
      host: 1.1.1.1
      count: 3

  - id: authoritative-dns
    name: Authoritative DNS
    type: dns
    groups: [Network]
    interval: 5m
    config:
      host: example.com
      record_type: A
      resolver: 1.1.1.1

  - id: public-cert-check
    name: GitHub Certificate Check
    type: ssl
    groups: [Security]
    interval: 6h
    config:
      host: github.com
      port: 443
      days_before_expiry: 21

  - id: github-ssh
    name: GitHub SSH Banner
    type: ssh
    groups: [Infra]
    interval: 5m
    config:
      host: github.com
      port: 22

  - id: public-tcp-port
    name: GitHub HTTPS Port
    type: tcp
    groups: [Edge]
    interval: 2m
    config:
      host: github.com
      port: 443

  - id: public-dns-udp
    name: Public DNS UDP
    type: udp
    groups: [Network]
    interval: 5m
    config:
      host: 1.1.1.1
      port: 53

  - id: github-routing
    name: GitHub WWW Routing
    type: dns_http
    groups: [Edge]
    interval: 5m
    config:
      url: https://www.github.com
      expected_cname: github.com
      expected_status: 200
      expected_body: GitHub
