monitors:
  - id: wan-ping
    name: Cloudflare Anycast Ping
    type: ping
    groups: [Network]
    interval: 1m
    config:
      host: 1.1.1.1
      count: 3

  - id: authoritative-dns
    name: Authoritative DNS
    type: dns
    groups: [Network]
    interval: 5m
    config:
      host: example.com
      record_type: A
      resolver: 1.1.1.1

  - id: public-tcp-port
    name: GitHub HTTPS Port
    type: tcp
    groups: [Edge]
    interval: 2m
    config:
      host: github.com
      port: 443
