monitors:
  - id: wan-ping
    name: WAN Ping
    type: ping
    groups: [Network]
    interval: 1m
    config:
      host: 1.1.1.1

  - id: authoritative-dns
    name: Authoritative DNS
    type: dns
    groups: [Network]
    interval: 5m
    config:
      host: example.com
      record_type: A
      resolver: 1.1.1.1

  - id: smtp-port
    name: SMTP TCP Port
    type: tcp
    groups: [Network]
    interval: 2m
    config:
      host: mail.example.com
      port: 25